system:
  num_client: 3
  num_local_class: 5
  dataset: "MNIST"
  model: "Linear"
  divide_method: "DropClass"
  i_seed: 235235
  num_round: 50
  res_root: "results"

client:
  fed_algo: "FedTest"
  lr: 0.1
  batch_size: 64
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 4