system:
  num_client: 3
  dataset: "CIFAR10"
  divide_method: "Dirichlet"
  num_local_class: 1
  alpha: 0.1
  model: Linear
  i_seed: 235235
  num_round: 5
  res_root: "results"
  x: 0.1

client:
  fed_algo: "FedProx_Plus"
  lr: 0.1
  batch_size: 64
  num_local_epoch: 5
  momentum: 0.9
  num_worker: 4