system:
  num_client: 5
  dataset: "MNIST"
  divide_method: "DropClass"
  num_local_class: 1
  alpha: 0.9
  model: "Linear"
  i_seed: 235235
  num_round: 5
  res_root: "results"

client:
  fed_algo: "SCAFFOLD"
  lr: 0.1
  batch_size: 64
  num_local_epoch: 5
  momentum: 0.9
  num_worker: 4