system:
  num_client: 3
  dataset: "CIFAR10"
  divide_method: "Dirichlet"
  num_local_class: 1
  alpha: 0.9
  model: CNN
  i_seed: 235235
  num_round: 20
  res_root: "results/test"
  x: 0.9

client:
  fed_algo: "FedAvg"
  lr: 0.1
  batch_size: 256
  num_local_epoch: 20
  momentum: 0.9
  num_worker: 4