system:
  num_client: 5
  num_local_class: 7
  dataset: "MNIST"
  model: "Linear"
  i_seed: 235235
  num_round: 5
  res_root: "results"

client:
  fed_algo: "FedTest"
  lr: 0.1
  batch_size: 64
  num_local_epoch: 1
  momentum: 0.9
  num_worker: 4